# Site settings
title: Ty Keating
email: tyjkeating@gmail.com
description: "May we work to live and love what we do..."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: bontgoy
github_username:  bontgoy

# Build settings
markdown: kramdown
permalink: /:categories/:title
