# Site settings
title: Ty Keating
email: tyjkeating@gmail.com
description: "ideas are dry leaves waiting for a creative spark"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: bontgoy
github_username:  bontgoy

# Build settings
markdown: kramdown
permalink: /:categories/:title
