# Site settings
title: Ty Keating
email: tyjkeating@gmail.com
description: "Live Well and Treat Others Well"
baseurl: ""
url: "http://bontgoy.com"
twitter_username: bontgoy
github_username:  bontgoy

# Build settings
markdown: kramdown
permalink: /:categories/:title
